### ISSUE TITLE
Hi, The error when I ran the benchmark was as follows.Please help to see where the problem is.

### ISSUE THREAD

**Issue by strawberrySu** [memcached/mc-crusher#9]
# ../test-suites/test-nvdimm mm
numactl --cpunodebind=0 --membind=0 /root/memcached/memcached-1.5.12/memcached -u root -l 127.0.0.1 -t 32 -c 32000 -m 600000 -o no_lru_crawler -b 4096 -s /tmp/memcached.sock -l 127.0.0.1 -p 11211
memc started (main)
Can't use an undefined value as a symbol reference at Memcached/McCrusher.pm line 105.
Signal handled: Terminated.

command as follows:
`$server_args = '-u root -l 127.0.0.1 -t 32 -c 32000 -m 600000 -o no_lru_crawler -b 4096 -s /tmp/memcached.sock';`

**Comment by dormando** [comment]
can you post a gist of the full script you're trying to run? that looks like the warm function isn't being used right.

**Comment by strawberrySu** [comment]
I changed the test-nvdimm script based on my test environment with no other changes, such as test directory, memory size.
`if ($TEST_TYPE eq 'dram') {
    $server_args = '-u root -l 127.0.0.1 -t 32 -c 32000 -m 70000 -o no_lru_crawler -b 4096 -s /tmp/memcached.sock';
} elsif ($TEST_TYPE eq 'pmem') {
    $server_args = '-u root -l 127.0.0.1 -t 32 -c 32000 -m 600000 -o no_lru_crawler -b 4096 -s /tmp/memcached.sock -e /pmem/mc/memc_mmap';
} elsif ($TEST_TYPE eq 'mm') {
    $server_args = '-u root -l 127.0.0.1 -t 32 -c 32000 -m 600000 -o no_lru_crawler -b 4096 -s /tmp/memcached.sock';
}
`
The command is as follows.
../test-suites/test-nvdimm mm

**Comment by dormando** [comment]
sorry, I wasn't able to help :(
